version: 1
disabled_existing_loggers: false
formatters:
  verbose:
    format: "%(levelname)-10s - %(asctime)s - %(module-15s) : %(message)s"
  standard:
    format: "%(levelname)-10s - %(name)s : %(message)s"
handlers:
  console:
    level: "DEBUG"
    class: "logging.StreamHandler"
    formatter: "simple"
  console2:
    level: "WARNING"
    class: "logging.StreamHandler"
    formatter: "simple"
  file:
    level: "INFO"
    class: "logging.FileHandler"
    filename: "logs/infos.log"
    mode: "w"
loggers:
  bot:
    handlers: ["console"]
    level: "INFO"
    propagate: false
  discord:
    handlers: ["console2", "file"]
    level: "INFO"
    propagate: false
# continue here: https://www.youtube.com/watch?v=ilNStiHY0Io
