services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: boggart-postgres
    ports:
      - "5432:5432"
    volumes:
      - "${PWD}/db:/docker-entrypoint-initdb.d/"
      - boggart-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - boggart-network
    restart: always

  boggart:
    build:
      dockerfile: Dockerfile
      tags: 
        - boggart:local
    image: boggart:local
    container_name: boggart
    volumes:
      - ${PWD}/prompt_templates:/prompt_templates
      - "${BOGGART_IMAGES_PATH}:/images"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_DALLE_MODEL: ${OPENAI_DALLE_MODEL}
      OPENAI_DALLE_IMAGE_SIZE: ${OPENAI_DALLE_IMAGE_SIZE}
      OPENAI_DALLE_IMAGE_QUALITY: ${OPENAI_DALLE_IMAGE_QUALITY}
      DISCORD_BOT_KEY: ${DISCORD_BOT_KEY}
      DISCORD_IMAGE_CHANNEL: ${DISCORD_IMAGE_CHANNEL}
      PG_CONNECTION: "postgresql+asyncpg://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}"
      OLLAMA_ENDPOINT_URL: ${OLLAMA_ENDPOINT_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL} 
    networks:
      - boggart-network
    depends_on:
      - postgres
    restart: always

networks:
  boggart-network:

volumes:
  boggart-postgres:
