# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import pydantic
from typing import Any, Optional


class Embedding(pydantic.BaseModel):
    id: int
    image_id: int
    prompt_embedding: Optional[Any]
    caption_embedding: Optional[Any]


class GeneratedImage(pydantic.BaseModel):
    id: int
    image_file: str
    time_created: Any
    prompt: str
    caption: str
