CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS Users (
    UserID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    Username VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS GeneratedImages (
    ImageID SERIAL PRIMARY KEY,
    ImageLink VARCHAR(255) UNIQUE NOT NULL,
    TimeCreated TIMESTAMPTZ NOT NULL,
    UserID UUID NOT NULL,
    Prompt TEXT NOT NULL,
    Caption TEXT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

INSERT INTO Users (Username)
VALUES
    ('chndlr');