openai: 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
discord: MTE1Njc1MTAyNTI5NDgwNzA4Mw.G8m-kN.mEQqrMdOYemURASpQNkcBGx3yD3a34DituATmg
backblaze:
  endpoint_url: https://s3.us-east-005.backblazeb2.com
  application_key_id: 005db1d17f3816d0000000003
  application_key: K005XGxbPhO6NOyzoOWUxPQhtoUQzb4
