openai: 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
discord: MTE4NDcwOTYxNzM0ODAwMTg3NA.GUSSh2.6xghgjwFBQLks2ZQoYAthVg2gBJOoZ_Q-q33Jw
backblaze:
  endpoint_url: https://s3.us-east-005.backblazeb2.com
  application_key_id: 005db1d17f3816d0000000003
  application_key: K005XGxbPhO6NOyzoOWUxPQhtoUQzb4
