import aiohttp
import asyncio
import boto3
import discord
import io
import uuid
from discord.ext import commands
from openai import OpenAI
from botocore.exceptions import NoCredentialsError

class ImageGenerator(commands.Cog):
    """
    Discord.py Cog for generating images using OpenAI DALLE
    """
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self.db = Database(pg_username='postgres',
            pg_password='chandlerb',
            pg_db='postgres',
            host='127.0.0.1:5432')

    async def generate_image(self, **kwargs: str):
        """
        Generates an image result from the provided prompt using the OpenAI API `client.images.generate()`.
        """
        prompt = kwargs.get('prompt')
        image_size = kwargs.get('image_size')
        image_quality = kwargs.get('image_quality')

        client = OpenAI()
        result = client.images.generate(model=self.dalle_model,
                                        prompt=prompt,
                                        n=1, size=image_size,
                                        quality=image_quality)
        return result

    async def download_image(self, ctx, url):
        """
        Download the `.png` image generated by OpenAI API using the temporary link provided. Returns type `io.BytesIO` if successful.

        Arguments:
        - `ctx`: Discord message context
        - `url`: Temporary URL provided by OpenAI API call
        """
        async with aiohttp.ClientSession() as session:
            async with session.get(url) as response:
                if response.status != 200:
                    await ctx.send("Failed to download the image.")
                    return
                image_data = await response.read()
                return io.BytesIO(image_data)
    
    # considering using **kwargs here
    async def upload_generated_image(self, image_data: io.BytesIO, b2_filename: str, bucket_name: str) -> bool:
        """
        Upload generated image to object storage using the `boto3` AWS API.
        
        Arguments:
        - `image_data`: The image data as a `io.BytesIO` object
        - `image_name`: Filename of the uploaded image
        - `bucket_name`: Name of storage bucket being 
        """
        image_data.seek(0)
        try:
            b2 = boto3.client('s3')
            b2.put_object(Bucket=bucket_name,
                        Key=b2_filename,
                        Body=image_data)
            return True

        except NoCredentialsError as e:
            print("Credentials not available")
            return False
            
    @commands.Cog.listener()
    async def on_ready(self):
        """
        Logs that the ImageGenerator "Cog" is Online
        """
        print("DiscordGPT Image Generator Ready\n")

    @commands.command()
    async def img(self, ctx, *, prompt):
        """
        Chat command for user to generate a 1024x1024 image using DALLE 3 Standard.
        """
        if str(ctx.message.channel) != 'boggart':
            return
        
        filename = f"{uuid.uuid1().hex}.png"
        
        # TODO: log that image request was recieved by 'x' user

        try:
            image_result = await self.generate_image(prompt=str(prompt),
                                                     image_size='1024x1024',
                                                     image_quality='standard')
        except Exception as e:
            await ctx.send(f"Error generating image: {e}")
            return
        
        try:
            image = await self.download_image(ctx, image_result.data[0].url)
        except Exception as e:
            await ctx.send(f"Error downloading image: {e}")
            return

        try:
            async with asyncio.TaskGroup() as upload:
                # send to discord chat
                upload.create_task(ctx.send(image_result.data[0].revised_prompt,
                                            file=discord.File(fp=image, filename=filename)))
                # upload to backblaze
                upload.create_task(self.upload_generated_image(image_data=image,
                                                               b2_filename=filename,
                                                               bucket_name='boggart'))
                # store reference to file in database
                upload.create_task(self.db.store_generated_image(b2_filename=filename,
                                                                 username=ctx.message.author.display_name,
                                                                 prompt=prompt,
                                                                 caption=image_result.data[0].revised_prompt))
        except Exception as e:
            await ctx.send(f"Error sending/storing image: {e}")
            return

    @commands.command()
    async def img_hd(self, ctx, *, prompt):
        """
        Chat command for user to generate a 1792x1024 image using DALLE 3 HD
        """
        if str(ctx.message.channel) != 'boggart':
            return

        # TODO: log that image request was recieved by 'x' user

        try:
            image_result = await self.generate_image(prompt=str(prompt),
                                                     image_size='1792x1024',
                                                     image_quality='hd')

        except Exception as e:
            await ctx.send(f"Error generating image: {e}")
            return

        try:
            filename = f"{ctx.message.author.display_name}.png"
            image = await self.download_image(ctx, image_result.data[0].url)
            await ctx.send(image_result.data[0].revised_prompt,
                           file=discord.File(fp=image, filename=filename))

        except Exception as e:
            await ctx.send(f"Error sending image: {e}")

async def setup(bot):
    await bot.add_cog(ImageGenerator(bot))