---
- name: Build Boggart Containers
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Login to Container Registry
      containers.podman.podman_login:
        username: "{{ podman.registry_username }}"
        password: "{{ podman.registry_password }}"
        registry: "{{ podman.registry }}"

    - name: Build Bot Container Image
      containers.podman.podman_image:
        name: "{{ boggart.container_image }}"
        tag: "{{ boggart.container_tag }}"
        pull: false
        path: ../src
        build:
          cache: false
        state: build

    - name: Push Bot Image
      containers.podman.podman_image:
        name: "{{ boggart.container_image }}"
        tag: "{{ boggart.container_tag }}"
        pull: false
        push: true

    - name: Build Database Image
      containers.podman.podman_image:
        name: "{{ postgres.container_tag }}"
        tag: "{{ postgres.container_tag }}"
        pull: false
        path: ../database
        build:
          cache: false
        state: build

    - name: Push Database Image
      containers.podman.podman_image:
        name: "{{ postgres.container_image }}"
        tag: "{{ postgres.container_tag }}"
        pull: false
        push: true
