---
- name: Build Boggart Containers
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Login to Container Registry
      containers.podman.podman_login:
        username: "{{ podman.registry_username }}"
        password: "{{ podman.registry_password }}"
        registry: "{{ podman.registry }}"
      tags:
        - registry
        - registry-login

    - name: Build Bot Container Image
      containers.podman.podman_image:
        name: "{{ boggart.container_image }}"
        tag: "{{ boggart.container_tag }}"
        pull: false
        path: ../src
        build:
          cache: false
        state: build
      tags:
        - bot
        - bot-build

    - name: Build Database Image
      containers.podman.podman_image:
        name: "{{ postgres.container_image }}"
        tag: "{{ postgres.container_tag }}"
        path: ../database
        build:
          cache: false
        state: build
      tags:
        - db
        - db-build

    - name: Push Bot Image
      containers.podman.podman_image:
        name: "{{ boggart.container_image }}"
        tag: "{{ boggart.container_tag }}"
        pull: false
        push: true
      tags:
        - bot
        - bot-push

    - name: Push Database Image
      containers.podman.podman_image:
        name: "{{ postgres.container_image }}"
        tag: "{{ postgres.container_tag }}"
        pull: false
        push: true
      tags:
        - db
        - db-push
