---
- name: Clean Boggart Podman Secrets
  hosts: all
  gather_facts: false

  tasks:
    - name: Clean OpenAI API Key Secret
      containers.podman.podman_secret:
        state: absent
        name: openai_api_key

    - name: Clean OpenAI DALLE Model Secret
      containers.podman.podman_secret:
        state: absent
        name: openai_dalle_model

    - name: Clean OpenAI DALLE Model Secret
      containers.podman.podman_secret:
        state: absent
        name: openai_dalle_image_size

    - name: Clean OpenAI DALLE Image Quality Secret
      containers.podman.podman_secret:
        state: absent
        name: openai_dalle_image_quality

    - name: Clean Discord Bot Key Secret
      containers.podman.podman_secret:
        state: absent
        name: discord_bot_key

    - name: Clean Discord Image Channel Secret
      containers.podman.podman_secret:
        state: absent
        name: discord_image_channel

    - name: Clean Backblaze Endpoint URL Secret
      containers.podman.podman_secret:
        state: absent
        name: backblaze_endpoint_url

    - name: Clean Backblaze Application Key ID Secret
      containers.podman.podman_secret:
        state: absent
        name: backblaze_application_key_id

    - name: Clean Backblaze Application Key Secret
      containers.podman.podman_secret:
        state: absent
        name: backblaze_application_key

    - name: Clean Backblaze Application Key Secret
      containers.podman.podman_secret:
        state: absent
        name: backblaze_bucket_name

    - name: Clean Postgres Username Secret
      containers.podman.podman_secret:
        state: absent
        name: postgres_username

    - name: Clean Postgres Password Secret
      containers.podman.podman_secret:
        state: absent
        name: postgres_password

    - name: Clean Postgres Database Name Secret
      containers.podman.podman_secret:
        state: absent
        name: postgres_database

    - name: Clean Postgres Hostname Secret
      containers.podman.podman_secret:
        state: absent
        name: postgres_host

    - name: Clean Postgres Port Secret
      containers.podman.podman_secret:
        state: absent
        name: postgres_port
