---
- name: Create Podman Secrets for Boggart
  hosts: all
  gather_facts: false

  tasks:
    - name: Create OpenAI API Key Secret
      containers.podman.podman_secret:
        state: present
        name: openai_api_key
        data: "{{ openai.api_key }}"
        skip_existing: true

    - name: Create OpenAI DALLE Model Secret
      containers.podman.podman_secret:
        state: present
        name: openai_dalle_model
        data: "{{ openai.dalle_model }}"
        skip_existing: true

    - name: Create OpenAI DALLE Model Secret
      containers.podman.podman_secret:
        state: present
        name: openai_dalle_image_size
        data: "{{ openai.dalle_image_size }}"
        skip_existing: true

    - name: Create OpenAI DALLE Image Quality Secret
      containers.podman.podman_secret:
        state: present
        name: openai_dalle_image_quality
        data: "{{ openai.dalle_image_quality }}"
        skip_existing: true

    - name: Create Discord Bot Key Secret
      containers.podman.podman_secret:
        state: present
        name: discord_bot_key
        data: "{{ discord.bot_key }}"
        skip_existing: true

    - name: Create Discord Image Channel Secret
      containers.podman.podman_secret:
        state: present
        name: discord_image_channel
        data: "{{ discord.image_channel }}"
        skip_existing: true

    - name: Create Backblaze Endpoint URL Secret
      containers.podman.podman_secret:
        state: present
        name: backblaze_endpoint_url
        data: "{{ backblaze.endpoint_url }}"
        skip_existing: true

    - name: Create Backblaze Application Key ID Secret
      containers.podman.podman_secret:
        state: present
        name: backblaze_application_key_id
        data: "{{ backblaze.application_key_id }}"
        skip_existing: true

    - name: Create Backblaze Application Key Secret
      containers.podman.podman_secret:
        state: present
        name: backblaze_application_key
        data: "{{ backblaze.application_key }}"
        skip_existing: true

    - name: Create Backblaze Application Key Secret
      containers.podman.podman_secret:
        state: present
        name: backblaze_bucket_name
        data: "{{ backblaze.bucket_name }}"
        skip_existing: true

    - name: Create Postgres Username Secret
      containers.podman.podman_secret:
        state: present
        name: postgres_username
        data: "{{ postgres.username }}"
        skip_existing: true

    - name: Create Postgres Password Secret
      containers.podman.podman_secret:
        state: present
        name: postgres_password
        data: "{{ postgres.password }}"
        skip_existing: true

    - name: Create Postgres Database Name Secret
      containers.podman.podman_secret:
        state: present
        name: postgres_database
        data: "{{ postgres.database }}"
        skip_existing: true

    - name: Create Postgres Hostname Secret
      containers.podman.podman_secret:
        state: present
        name: postgres_host
        data: "{{ postgres.host }}"
        skip_existing: true

    - name: Create Postgres Port Secret
      containers.podman.podman_secret:
        state: present
        name: postgres_port
        data: "{{ postgres.port }}"
        skip_existing: true
